name: Continuous Integration

permissions:
  contents: write
  pull-requests: write

on:
  pull_request:
    branches:
    - main
    - develop
    - environment/*
    types: [opened, reopened, synchronize]

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: run code check
        run: |
          echo 'formt, lint, ut and more'
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: run code check
        run: |
          echo 'e2e'
